[package]
name = "ai-powered-db"
version = "0.1.0"
edition = "2024"

[dependencies]
async-compression = { version = "0.4.25", features = ["tokio", "zstd"] }
byteorder = "1.5.0"
crc32fast = "1.4.2"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread", "fs", "io-util"] }
